In [2]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
import seaborn as sns

In [3]:
df=pd.read_csv('sales_transactions.csv')
df.head()

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
0,T108225,2025-02-14,P0009,C00202,NaN,5.0,11247.70,0.20,44990.8
1,T103133,03/08/2023,P0033,C00001,West,4.0,10082.29,0.20,32263.33
2,T101446,2023-08-03,P0039,C00018,Central,3.0,14579.92,0.05,41552.77
3,T104568,07-Jul-2024,P0016,C00213,NaN,7.0,2604.21,0.15,15495.05
4,T106022,2024-01-09,P0020,C00238,West,1.0,4508.30,0.00,4508.3

In [4]:
df.shape

(9120, 9)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9120 entries, 0 to 9119
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  9120 non-null   str
 1   date            9120 non-null   str
 2   product_id      9120 non-null   str
 3   customer_id     9120 non-null   str
 4   region          8613 non-null   str
 5   quantity        8937 non-null   str
 6   unit_price      8981 non-null   float64
 7   discount        8848 non-null   float64
 8   revenue         9120 non-null   str
dtypes: float64(2), str(7)
memory usage: 641.4 KB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
unit_price,8981.0,7976.974311,4276.357406,359.09,4999.13,8621.09,11247.70,14579.92
discount,8848.0,0.055708,0.573771,0.00,0.00,0.00,0.05,20.00

#### Check Duplicates

In [9]:
df.duplicated().sum()

27

In [10]:
df.drop_duplicates(inplace=True)

#### Check Null Values

In [12]:
nv=df.isnull().sum()
nv_df = nv[nv>0]
nv_df

region        505
quantity      182
unit_price    137
discount      272
dtype: int64

#### Check Columns

In [14]:
df.columns

Index(['transaction_id', 'date', 'product_id', 'customer_id', 'region',
       'quantity', 'unit_price', 'discount', 'revenue'],
      dtype='str')

In [16]:
df.dtypes

transaction_id        str
date                  str
product_id            str
customer_id           str
region                str
quantity              str
unit_price        float64
discount          float64
revenue               str
dtype: object

In [17]:
df['transaction_id'].head(5)

0    T108225
1    T103133
2    T101446
3    T104568
4    T106022
Name: transaction_id, dtype: str

In [18]:
df['date']

0        2025-02-14
1        03/08/2023
2        2023-08-03
3       07-Jul-2024
4        2024-01-09
           ...
9115     03/09/2024
9116     09/10/2025
9117     2025-12-07
9118     07/12/2023
9119     04/11/2025
Name: date, Length: 9093, dtype: str

In [19]:
df['date'] = pd.to_datetime(df['date'], format ='mixed' , errors ='coerce')

In [20]:
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [21]:
df['date'] = pd.to_datetime(df['date'],format = '%Y-%m-%d')

In [26]:
df['customer_id'].isnull().sum()

0

In [28]:
df['region'].head(10)

0        NaN
1       West
2    Central
3        NaN
4       West
5       West
6      South
7       East
8      South
9       West
Name: region, dtype: str

In [31]:
df['region'].value_counts()

region
Central      1714
East         1680
West         1571
North        1560
South        1475
SOUTH         180
 East         162
north         157
east           13
central        12
south          11
Central        11
west           10
West            9
East            9
South           5
North           4
 east           2
south           2
 East           1
Name: count, dtype: int64

In [33]:
df['region'] = df['region'].str.lower().str.strip()

In [34]:
df['region'].value_counts()

region
east       1867
central    1737
north      1721
south      1673
west       1590
Name: count, dtype: int64

In [45]:
df['unit_price'].isnull().sum()

137

In [46]:
df['unit_price'].value_counts()

unit_price
8863.25     272
5656.65     268
6013.99     251
12773.07    243
382.20      243
7884.39     242
14423.40    237
2604.21     236
499.00      235
12756.37    234
8930.77     233
14579.92    232
500.00      232
13905.57    230
10038.95    230
8621.09     228
6017.98     227
11884.11    227
359.09      227
9148.51     227
13910.88    225
9164.46     224
14484.04    222
10713.43    221
10949.99    219
3102.81     217
4229.62     216
4508.30     214
4999.13     214
6437.51     214
11247.70    213
4549.66     213
10082.29    210
9818.49     209
8484.46     206
5836.46     199
6824.34     198
13737.15    196
8164.43     189
1566.84     183
Name: count, dtype: int64

In [52]:
df['revenue'].value_counts()

revenue
51092.28    38
23653.17    37
35652.33    35
18053.94    35
32140.29    35
            ..
2800.0       1
100148.6     1
45706.32     1
76928.04     1
₹718.18      1
Name: count, Length: 1886, dtype: int64

In [49]:
df['revenue'].isnull().sum()

0

In [53]:
df['revenue'] = df['revenue'].str.replace(",","")

In [54]:
df['revenue'] = df['revenue'].str.replace("₹","")

In [55]:
df['revenue'] = pd.to_numeric(df['revenue'])

In [57]:
df[df['transaction_id']=="T100149"]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
832,T100149,2023-01-17,P0026,C00028,central,2.0,13905.57,NaN,23639.47

In [58]:
df['discount'].isnull().sum()

272

In [63]:
expected_discount = (df['unit_price'] * df['quantity'] - df['revenue']) / (df['unit_price'] * df['quantity'])

df['discount'] = df['discount'].fillna(expected_discount)

In [64]:
df['discount'].isnull().sum()

6

In [65]:
df[df['discount'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
1517,T104229,2023-09-05,P0001,C00109,north,NaN,6017.98,NaN,24071.92
2351,T101984,2025-08-02,P0001,C00078,west,NaN,6017.98,NaN,18053.94
2518,T103658,2024-02-06,P0031,C00146,central,3.0,NaN,NaN,4700.52
3673,T101956,2023-10-23,P0010,C00096,central,2.0,NaN,NaN,15512.42
6441,T102993,2024-10-03,P0010,C00038,west,NaN,8164.43,NaN,22043.96
7873,T103640,2025-01-07,P0025,C00131,west,7.0,NaN,NaN,64039.57

In [37]:
df['quantity'].value_counts()

quantity
3.0        1588
4.0        1502
2.0        1060
1.0         994
5.0         955
6.0         949
7.0         685
8.0         416
9.0         276
10.0        144
11.0        133
13.0         56
12.0         55
14.0         20
-4.0         12
16.0         11
-3.0          9
unknown       8
17.0          7
15.0          7
-1.0          6
19.0          3
-5.0          2
-6.0          2
-10.0         2
-2.0          2
-8.0          2
-9.0          1
18.0          1
20.0          1
-7.0          1
22.0          1
Name: count, dtype: int64

In [38]:
df['quantity'] = df['quantity'].str.replace("-","")

In [61]:
# Replace 'unknown' with NaN and cast quantity to numeric
df['quantity'] = pd.to_numeric(df['quantity'].replace('unknown', np.nan))

In [68]:
expected_qty = round((df['discount']*df['revenue']+df['revenue'])/df['unit_price'])

In [69]:
df['quantity'].isnull().sum()

190

In [71]:
df['quantity']=df['quantity'].fillna(expected_qty)

In [72]:
df['quantity'].isnull().sum()

6

In [73]:
df[df['quantity'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
1517,T104229,2023-09-05,P0001,C00109,north,NaN,6017.98,NaN,24071.92
2351,T101984,2025-08-02,P0001,C00078,west,NaN,6017.98,NaN,18053.94
4350,T108878,2024-02-23,P0025,C00025,south,NaN,NaN,0.05,34764.34
6441,T102993,2024-10-03,P0010,C00038,west,NaN,8164.43,NaN,22043.96
7637,T101418,2024-06-02,P0013,C00067,NaN,NaN,NaN,0.00,36657.84
8096,T103300,2023-05-06,P0004,C00242,east,NaN,NaN,0.00,14997.39

In [74]:
df['quantity']=df['quantity'].fillna(round(df['revenue']/df['unit_price']))

In [75]:
df['quantity'].isnull().sum()

3

In [76]:
df[df['quantity'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
4350,T108878,2024-02-23,P0025,C00025,south,NaN,NaN,0.05,34764.34
7637,T101418,2024-06-02,P0013,C00067,NaN,NaN,NaN,0.00,36657.84
8096,T103300,2023-05-06,P0004,C00242,east,NaN,NaN,0.00,14997.39

In [77]:
df['discount'].isnull().sum()

6

In [78]:
df[df['discount'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
1517,T104229,2023-09-05,P0001,C00109,north,4.0,6017.98,NaN,24071.92
2351,T101984,2025-08-02,P0001,C00078,west,3.0,6017.98,NaN,18053.94
2518,T103658,2024-02-06,P0031,C00146,central,3.0,NaN,NaN,4700.52
3673,T101956,2023-10-23,P0010,C00096,central,2.0,NaN,NaN,15512.42
6441,T102993,2024-10-03,P0010,C00038,west,3.0,8164.43,NaN,22043.96
7873,T103640,2025-01-07,P0025,C00131,west,7.0,NaN,NaN,64039.57

In [81]:
expected_discount = (df['unit_price'] * df['quantity'] - df['revenue']) / (df['unit_price'] * df['quantity'])

df['discount'] = df['discount'].fillna(expected_discount)

In [82]:
df['discount'].isnull().sum()

3

In [83]:
df[df['quantity'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
4350,T108878,2024-02-23,P0025,C00025,south,NaN,NaN,0.05,34764.34
7637,T101418,2024-06-02,P0013,C00067,NaN,NaN,NaN,0.00,36657.84
8096,T103300,2023-05-06,P0004,C00242,east,NaN,NaN,0.00,14997.39

In [88]:
df.head(1)

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
0,T108225,2025-02-14,P0009,C00202,NaN,5.0,11247.7,0.2,44990.8

In [89]:
expected_unit_price = df['revenue'] / (df['quantity'] * (1 - df['discount']))
df['unit_price'] = df['unit_price'].fillna(expected_unit_price)

In [91]:
df[df['unit_price'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
2518,T103658,2024-02-06,P0031,C00146,central,3.0,NaN,NaN,4700.52
3673,T101956,2023-10-23,P0010,C00096,central,2.0,NaN,NaN,15512.42
4350,T108878,2024-02-23,P0025,C00025,south,NaN,NaN,0.05,34764.34
7637,T101418,2024-06-02,P0013,C00067,NaN,NaN,NaN,0.00,36657.84
7873,T103640,2025-01-07,P0025,C00131,west,7.0,NaN,NaN,64039.57
8096,T103300,2023-05-06,P0004,C00242,east,NaN,NaN,0.00,14997.39

In [93]:
df['unit_price'] = df['unit_price'].fillna(round(df['revenue']/df['quantity']))

In [94]:
df[df['unit_price'].isnull()]

,transaction_id,date,product_id,customer_id,region,quantity,unit_price,discount,revenue
4350,T108878,2024-02-23,P0025,C00025,south,NaN,NaN,0.05,34764.34
7637,T101418,2024-06-02,P0013,C00067,NaN,NaN,NaN,0.00,36657.84
8096,T103300,2023-05-06,P0004,C00242,east,NaN,NaN,0.00,14997.39

In [95]:
nv = df.isnull().sum()
nv_df = nv[nv>0]
nv_df

region        505
quantity        3
unit_price      3
discount        3
dtype: int64

In [97]:
df['region'].value_counts(normalize=True)

region
east       0.217396
central    0.202259
north      0.200396
south      0.194807
west       0.185142
Name: proportion, dtype: float64

In [98]:
probs = df['region'].value_counts(normalize=True)

In [99]:
missing_mask = df['region'].isnull()
df.loc[missing_mask, 'region'] = np.random.choice(probs.index, size=missing_mask.sum(), p=probs.values)

In [100]:
df['region'].isnull().sum()

0

In [101]:
df.dropna(inplace=True)

In [103]:
df.to_csv('sales_transactions_cleaned.csv',index=False)