# Model Training Notebook
### Sales Forecasting & Gen AI Project

## 1. Librariers Imports

In [1]:
import pandas as pd
import numpy as np

C:\Users\shahi\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.4' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\shahi\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
pd.set_option('display.max_columns', None)

## 2. Connect to MySQL & Load Feature Table

In [3]:
from urllib.parse import quote_plus

In [4]:
from sqlalchemy import create_engine

In [5]:
DB_USER = "root"
DB_PASSWORD = quote_plus("your password") 
DB_HOST = "localhost"
DB_PORT = 3306
DB_NAME = "you data base name"

connection_string = f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine = create_engine(connection_string)

with engine.connect() as conn:
    df = pd.read_sql("SELECT * FROM feature_table", conn)

print("Shape:", df.shape)
df.head()

Shape: (36, 21)

,year,month,total_revenue,order_count,active_customers,quarter,revenue_lag_1,revenue_lag_3,revenue_lag_12,rolling_mean_3,rolling_mean_6,rolling_std_3,mom_growth_pct,yoy_growth_pct,is_festive_month,avg_discount,avg_order_value,repeat_customer_rate,top_category,top_category_share,target_revenue
0,2023,1,6282761.26,243,153,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.029,25854.98,35.39,home & kitchen,0.297,NaN
1,2023,2,5584972.24,198,124,1,6282761.26,NaN,NaN,NaN,NaN,NaN,-11.11,NaN,0,0.040,28206.93,76.77,home & kitchen,0.511,NaN
2,2023,3,7225276.49,244,150,1,5584972.24,NaN,NaN,6.364337e+06,NaN,8.231892e+05,29.37,NaN,0,0.040,29611.79,86.89,home & kitchen,0.423,NaN
3,2023,4,10616603.50,230,147,2,7225276.49,6282761.26,NaN,7.808951e+06,NaN,2.566093e+06,46.94,NaN,0,0.033,46159.15,94.35,sports,0.476,NaN
4,2023,5,12021876.44,262,166,2,10616603.50,5584972.24,NaN,9.954585e+06,NaN,2.465876e+06,13.24,NaN,0,0.032,45885.02,98.09,grocery,0.417,NaN

## 3. Clean Rows with Missing Lag Values

In [6]:
df = df.sort_values(['year', 'month']).reset_index(drop=True)

before_rows = df.shape[0]
df_model = df.dropna().reset_index(drop=True)
after_rows = df_model.shape[0]

print(f"Rows before: {before_rows} | Rows after dropping NaN: {after_rows}")
df_model.head()

Rows before: 36 | Rows after dropping NaN: 24

,year,month,total_revenue,order_count,active_customers,quarter,revenue_lag_1,revenue_lag_3,revenue_lag_12,rolling_mean_3,rolling_mean_6,rolling_std_3,mom_growth_pct,yoy_growth_pct,is_festive_month,avg_discount,avg_order_value,repeat_customer_rate,top_category,top_category_share,target_revenue
0,2024,1,6528003.42,276,166,1,13741610.83,9224626.01,6282761.26,1.051654e+07,9.960742e+06,3.666906e+06,-52.49,3.90,0,0.070,23652.19,100.0,home & kitchen,0.383,2000000.0
1,2024,2,5266690.87,217,141,1,6528003.42,11280009.98,5584972.24,8.512102e+06,8.974701e+06,4.572587e+06,-19.32,-5.70,0,0.029,24270.46,100.0,home & kitchen,0.294,2125000.0
2,2024,3,8084247.51,253,152,1,5266690.87,13741610.83,7225276.49,6.626314e+06,9.020865e+06,1.411349e+06,53.50,11.89,0,0.047,31953.55,100.0,home & kitchen,0.360,2500000.0
3,2024,4,8383036.20,250,157,2,8084247.51,6528003.42,10616603.50,7.244658e+06,8.880600e+06,1.719472e+06,3.70,-21.04,0,0.034,33532.14,100.0,home & kitchen,0.420,2500000.0
4,2024,5,8797381.85,263,162,2,8383036.20,5266690.87,12021876.44,8.421555e+06,8.466828e+06,3.581242e+05,4.94,-26.82,0,0.094,33450.12,100.0,home & kitchen,0.405,2500000.0

## 4. Define Features (X) and Target (y)

In [7]:
feature_columns = [
    'month', 'quarter',
    'revenue_lag_1', 'revenue_lag_3', 'revenue_lag_12',
    'rolling_mean_3', 'rolling_mean_6', 'rolling_std_3',
    'mom_growth_pct', 'yoy_growth_pct',
    'avg_discount', 'order_count', 'avg_order_value',
    'active_customers', 'repeat_customer_rate',
    'top_category_share', 'is_festive_month'
]

X = df_model[feature_columns]
y = df_model['total_revenue']

print("X shape:", X.shape, "| y shape:", y.shape)
X.head()

X shape: (24, 17) | y shape: (24,)

,month,quarter,revenue_lag_1,revenue_lag_3,revenue_lag_12,rolling_mean_3,rolling_mean_6,rolling_std_3,mom_growth_pct,yoy_growth_pct,avg_discount,order_count,avg_order_value,active_customers,repeat_customer_rate,top_category_share,is_festive_month
0,1,1,13741610.83,9224626.01,6282761.26,1.051654e+07,9.960742e+06,3.666906e+06,-52.49,3.90,0.070,276,23652.19,166,100.0,0.383,0
1,2,1,6528003.42,11280009.98,5584972.24,8.512102e+06,8.974701e+06,4.572587e+06,-19.32,-5.70,0.029,217,24270.46,141,100.0,0.294,0
2,3,1,5266690.87,13741610.83,7225276.49,6.626314e+06,9.020865e+06,1.411349e+06,53.50,11.89,0.047,253,31953.55,152,100.0,0.360,0
3,4,2,8084247.51,6528003.42,10616603.50,7.244658e+06,8.880600e+06,1.719472e+06,3.70,-21.04,0.034,250,33532.14,157,100.0,0.420,0
4,5,2,8383036.20,5266690.87,12021876.44,8.421555e+06,8.466828e+06,3.581242e+05,4.94,-26.82,0.094,263,33450.12,162,100.0,0.405,0

## 5. Train-Test Split

In [8]:
test_size = 6

X_train = X.iloc[:-test_size]
X_test  = X.iloc[-test_size:]
y_train = y.iloc[:-test_size]
y_test  = y.iloc[-test_size:]

print("Train size:", X_train.shape[0], "| Test size:", X_test.shape[0])

Train size: 18 | Test size: 6

## 6. Reusable Accuracy Function

In [9]:
from sklearn.metrics import mean_absolute_percentage_error, root_mean_squared_error

In [10]:
results = {}

def evaluate_model(model_name, y_true, y_pred):
    mape = mean_absolute_percentage_error(y_true, y_pred) * 100
    rmse = root_mean_squared_error(y_true, y_pred)

    results[model_name] = {'MAPE (%)': round(mape, 2), 'RMSE': round(rmse, 2)}

    print(f"{model_name}")
    print(f"  MAPE: {mape:.2f}%")
    print(f"  RMSE: {rmse:.2f}")

    return mape, rmse

## 7. Baseline Model — Naive Seasonal

In [11]:
baseline_pred = X_test['revenue_lag_12'].values

In [12]:
evaluate_model("Baseline (Naive Seasonal)", y_test.values, baseline_pred)

Baseline (Naive Seasonal)
  MAPE: 17.84%
  RMSE: 2748209.13

(17.835843968720518, 2748209.1280557094)

## 8. Linear Regression

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)

In [15]:
evaluate_model("Linear Regression", y_test.values, lr_pred)

Linear Regression
  MAPE: 2.37%
  RMSE: 344677.89

(2.368584584607732, 344677.886920306)

## 9. XGBoost

In [16]:
from xgboost import XGBRegressor

In [17]:
xgb_simple = XGBRegressor(random_state=42)
xgb_simple.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [18]:
# Predictions
xgb_simple_pred = xgb_simple.predict(X_test)

In [19]:
evaluate_model("XGBoost (Simple)", y_test.values, xgb_simple_pred)

XGBoost (Simple)
  MAPE: 23.60%
  RMSE: 3237992.12

(23.598132399165173, 3237992.118964892)

## XGBoost — Hyperparameter Tuning

In [20]:
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit

In [21]:
xgb_param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [2, 3, 4],
    'learning_rate': [0.05, 0.1, 0.2]
}

tscv = TimeSeriesSplit(n_splits=3)

In [22]:
xgb_search = GridSearchCV(
    estimator=XGBRegressor(random_state=42),
    param_grid=xgb_param_grid,
    cv=tscv,
    scoring='neg_mean_absolute_percentage_error',
    n_jobs=-1
)

In [23]:
xgb_search.fit(X_train, y_train)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1, 0.2],
                         'max_depth': [2, 3, 4],
                         'n_estimators': [50, 100, 200]},
             scoring='neg_mean_absolute_percentage_error')

In [24]:
print("Best XGBoost parameters:", xgb_search.best_params_)

Best XGBoost parameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 200}

In [25]:
best_xgb_model = xgb_search.best_estimator_
xgb_pred = best_xgb_model.predict(X_test)

In [26]:
evaluate_model("XGBoost (Tuned)", y_test.values, xgb_pred)

XGBoost (Tuned)
  MAPE: 22.63%
  RMSE: 3003295.34

(22.633490757021782, 3003295.3358936813)

## 10. Random Forest — Hyperparameter Tuning

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:
rf_param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 4]
}

In [29]:
rf_search = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=rf_param_grid,
    cv=tscv,
    scoring='neg_mean_absolute_percentage_error',
    n_jobs=-1
)

In [30]:
rf_search.fit(X_train, y_train)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, None],
                         'min_samples_split': [2, 4],
                         'n_estimators': [50, 100, 200]},
             scoring='neg_mean_absolute_percentage_error')

In [31]:
print("Best Random Forest parameters:", rf_search.best_params_)

Best Random Forest parameters: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 100}

In [32]:
best_rf_model = rf_search.best_estimator_
rf_pred = best_rf_model.predict(X_test)

In [33]:
evaluate_model("Random Forest (Tuned)", y_test.values, rf_pred)

Random Forest (Tuned)
  MAPE: 5.37%
  RMSE: 665990.96

(5.370219251232253, 665990.9615964459)

## 11. Compare All Models

In [34]:
comparison_df = pd.DataFrame(results).T
comparison_df = comparison_df.sort_values('MAPE (%)')

print("Model Comparison (best model on top):")
comparison_df

Model Comparison (best model on top):

                           MAPE (%)        RMSE
Linear Regression              2.37   344677.89
Random Forest (Tuned)          5.37   665990.96
Baseline (Naive Seasonal)     17.84  2748209.13
XGBoost (Tuned)               22.63  3003295.34
XGBoost (Simple)              23.60  3237992.12

## 12. Feature Importance (Best Model)

In [71]:
best_model_name = comparison_df.index[0]
print("Best model:", best_model_name)

Best model: Linear Regression

In [36]:
from sklearn.linear_model import Ridge, Lasso

In [37]:
ridge_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}
ridge_search = GridSearchCV(Ridge(), ridge_grid, cv=tscv, scoring='neg_mean_absolute_percentage_error')

In [39]:
ridge_search.fit(X_train, y_train)

C:\Users\shahi\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:264: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 7.41994968417795e-18.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
C:\Users\shahi\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:264: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.417353286048567e-17.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
C:\Users\shahi\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:264: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.644905825569748e-17.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             estimator=Ridge(), param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_absolute_percentage_error')

In [40]:
print("Best Ridge alpha:", ridge_search.best_params_)

Best Ridge alpha: {'alpha': 100}

In [41]:
evaluate_model("Ridge (Tuned)", y_test.values, ridge_search.best_estimator_.predict(X_test))

Ridge (Tuned)
  MAPE: 2.81%
  RMSE: 398593.65

(2.8137842799983255, 398593.64963326656)

In [42]:
lasso_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}
lasso_search = GridSearchCV(Lasso(max_iter=5000), lasso_grid, cv=tscv, scoring='neg_mean_absolute_percentage_error')

In [43]:
lasso_search.fit(X_train, y_train)

C:\Users\shahi\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.669030e+10, tolerance: 1.513e+10
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             estimator=Lasso(max_iter=5000),
             param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_absolute_percentage_error')

In [44]:
print("Best Lasso alpha:", lasso_search.best_params_)

Best Lasso alpha: {'alpha': 100}

In [45]:
evaluate_model("Lasso (Tuned)", y_test.values, lasso_search.best_estimator_.predict(X_test))

Lasso (Tuned)
  MAPE: 4.11%
  RMSE: 546184.26

(4.11091663112356, 546184.2611286729)

In [47]:
comparison_df = pd.DataFrame(results).T
comparison_df = comparison_df.sort_values('MAPE (%)')

In [49]:
print("Model Comparison (best model on top):")
comparison_df

Model Comparison (best model on top):

                           MAPE (%)        RMSE
Linear Regression              2.37   344677.89
Ridge (Tuned)                  2.81   398593.65
Lasso (Tuned)                  4.11   546184.26
Random Forest (Tuned)          5.37   665990.96
Baseline (Naive Seasonal)     17.84  2748209.13
XGBoost (Tuned)               22.63  3003295.34
XGBoost (Simple)              23.60  3237992.12

In [50]:
import pickle

In [53]:
pickle.dump(lr_model,open("sales_forecast_model_LR.pkl",'wb'))

In [54]:
df_model

,year,month,total_revenue,order_count,active_customers,quarter,revenue_lag_1,revenue_lag_3,revenue_lag_12,rolling_mean_3,rolling_mean_6,rolling_std_3,mom_growth_pct,yoy_growth_pct,is_festive_month,avg_discount,avg_order_value,repeat_customer_rate,top_category,top_category_share,target_revenue
0,2024,1,6528003.42,276,166,1,13741610.83,9224626.01,6282761.26,1.051654e+07,9.960742e+06,3.666906e+06,-52.49,3.90,0,0.070,23652.19,100.0,home & kitchen,0.383,2000000.0
1,2024,2,5266690.87,217,141,1,6528003.42,11280009.98,5584972.24,8.512102e+06,8.974701e+06,4.572587e+06,-19.32,-5.70,0,0.029,24270.46,100.0,home & kitchen,0.294,2125000.0
2,2024,3,8084247.51,253,152,1,5266690.87,13741610.83,7225276.49,6.626314e+06,9.020865e+06,1.411349e+06,53.50,11.89,0,0.047,31953.55,100.0,home & kitchen,0.360,2500000.0
3,2024,4,8383036.20,250,157,2,8084247.51,6528003.42,10616603.50,7.244658e+06,8.880600e+06,1.719472e+06,3.70,-21.04,0,0.034,33532.14,100.0,home & kitchen,0.420,2500000.0
4,2024,5,8797381.85,263,162,2,8383036.20,5266690.87,12021876.44,8.421555e+06,8.466828e+06,3.581242e+05,4.94,-26.82,0,0.094,33450.12,100.0,home & kitchen,0.405,2500000.0
5,2024,6,8429387.84,269,160,2,8797381.85,8084247.51,7846609.33,8.536602e+06,7.581458e+06,2.270280e+05,-4.18,7.43,0,0.033,31336.01,100.0,home & kitchen,0.383,2500000.0
6,2024,7,7130056.75,249,160,3,8429387.84,8383036.20,9589366.48,8.118942e+06,7.681800e+06,8.759427e+05,-15.41,-25.65,0,0.077,28634.77,100.0,home & kitchen,0.352,2500000.0
7,2024,8,9381893.40,276,167,3,7130056.75,8797381.85,11182936.14,8.313779e+06,8.367667e+06,1.130361e+06,31.58,-16.11,0,0.034,33992.37,100.0,home & kitchen,0.352,2500000.0
8,2024,9,7895263.74,262,164,3,9381893.40,8429387.84,7807263.08,8.135738e+06,8.336170e+06,1.145017e+06,-15.85,1.13,0,0.088,30134.59,100.0,home & kitchen,0.332,2500000.0
9,2024,10,11531126.90,256,165,4,7895263.74,7130056.75,9224626.01,9.602761e+06,8.860852e+06,1.827967e+06,46.05,25.00,1,0.105,45043.46,100.0,home & kitchen,0.387,3500000.0
10,2024,11,11853897.33,250,151,4,11531126.90,9381893.40,11280009.98,1.042676e+07,9.370271e+06,2.198274e+06,2.80,5.09,1,0.033,47415.59,100.0,home & kitchen,0.418,4000000.0
11,2024,12,16146316.86,255,169,4,11853897.33,7895263.74,13741610.83,1.317711e+07,1.065643e+07,2.576465e+06,36.21,17.50,1,0.023,63318.89,100.0,sports,0.365,3750000.0
12,2025,1,6388053.41,241,161,1,16146316.86,11531126.90,6528003.42,1.146276e+07,1.053276e+07,4.890876e+06,-60.44,-2.14,0,0.055,26506.45,100.0,home & kitchen,0.333,2300000.0
13,2025,2,6571783.42,209,141,1,6388053.41,11853897.33,5266690.87,9.702051e+06,1.006441e+07,5.581654e+06,2.88,24.78,0,0.020,31443.94,100.0,home & kitchen,0.430,2444000.0
14,2025,3,8361547.00,244,152,1,6571783.42,16146316.86,8084247.51,7.107128e+06,1.014212e+07,1.090236e+06,27.23,3.43,0,0.096,34268.64,100.0,home & kitchen,0.428,2875000.0
15,2025,4,15696457.88,276,170,2,8361547.00,6388053.41,8383036.20,1.020993e+07,1.083634e+07,4.835009e+06,87.72,87.24,0,0.036,56871.22,100.0,home & kitchen,0.626,2875000.0
16,2025,5,10118594.94,276,165,2,15696457.88,6571783.42,8797381.85,1.139220e+07,1.054713e+07,3.829723e+06,-35.54,15.02,0,0.031,36661.58,100.0,home & kitchen,0.384,2875000.0
17,2025,6,8326845.06,256,157,2,10118594.94,8361547.00,8429387.84,1.138063e+07,9.243880e+06,3.843482e+06,-17.71,-1.22,0,0.075,32526.74,100.0,home & kitchen,0.405,2875000.0
18,2025,7,12490297.99,276,165,3,8326845.06,15696457.88,7130056.75,1.031191e+07,1.026092e+07,2.088448e+06,50.00,75.18,0,0.122,45254.70,100.0,electronics,0.334,2875000.0
19,2025,8,12102756.18,237,154,3,12490297.99,10118594.94,9381893.40,1.097330e+07,1.118275e+07,2.300074e+06,-3.10,29.00,0,0.031,51066.48,100.0,sports,0.546,2875000.0
20,2025,9,10132338.42,270,158,3,12102756.18,8326845.06,7895263.74,1.157513e+07,1.147788e+07,1.264431e+06,-16.28,28.33,0,0.034,37527.18,100.0,home & kitchen,0.334,2875000.0
21,2025,10,11242309.04,238,156,4,10132338.42,12490297.99,11531126.90,1.115913e+07,1.073552e+07,9.878386e+05,10.95,-2.50,1,0.036,47236.59,100.0,home & kitchen,0.411,4025000.0
22,2025,11,12207746.02,224,157,4,11242309.04,12102756.18,11853897.33,1.119413e+07,1.108372e+07,1.038542e+06,8.59,2.99,1,0.075,54498.87,100.0,home & kitchen,0.358,4600000.0
23,2025,12,14154455.35,274,171,4,12207746.02,10132338.42,16146316.86,1.253484e+07,1.205498e+07,1.483371e+06,15.95,-12.34,1,0.039,51658.60,100.0,home & kitchen,0.301,4312000.0

# Future Predictions

In [60]:
def predict_future_revenue(model, df, feature_cols, n_months=6):
    """
    Generates recursive future predictions for specified n_months.
    """
    future_preds = []
    current_row = df.iloc[-1:].copy()
    history_revenue = list(df['total_revenue'].values)
    
    for _ in range(n_months):
        # 1. Prediction
        next_pred = model.predict(current_row[feature_cols])[0]
        future_preds.append(next_pred)
        history_revenue.append(next_pred)
        
        # 2. Update Lag & Rolling Features
        current_row['revenue_lag_1'] = history_revenue[-1]
        current_row['revenue_lag_3'] = history_revenue[-3]
        current_row['revenue_lag_12'] = history_revenue[-12]
        
        current_row['rolling_mean_3'] = np.mean(history_revenue[-3:])
        current_row['rolling_mean_6'] = np.mean(history_revenue[-6:])
        current_row['rolling_std_3'] = np.std(history_revenue[-3:], ddof=1)
        
        current_row['mom_growth_pct'] = ((history_revenue[-1] - history_revenue[-2]) / history_revenue[-2]) * 100
        current_row['yoy_growth_pct'] = ((history_revenue[-1] - history_revenue[-13]) / history_revenue[-13]) * 100
        
        # 3. Update Calendar Features
        new_month = (current_row['month'].values[0] % 12) + 1
        current_row['month'] = new_month
        current_row['quarter'] = (new_month - 1) // 3 + 1
        current_row['is_festive_month'] = 1 if new_month in [10, 11, 12] else 0

    return future_preds

In [63]:
future_6_months = predict_future_revenue(lr_model, df_model, feature_columns, n_months=12)

# Print Output in Crores / Lakhs
for i, val in enumerate(future_6_months, 1):
    print(f"Month {i}: ₹{val:,.2f} ({val/1e7:.2f} Cr)")

Month 1: ₹13,648,553.92 (1.36 Cr)
Month 2: ₹13,747,700.25 (1.37 Cr)
Month 3: ₹13,769,167.52 (1.38 Cr)
Month 4: ₹14,036,279.85 (1.40 Cr)
Month 5: ₹12,717,068.84 (1.27 Cr)
Month 6: ₹12,926,435.61 (1.29 Cr)
Month 7: ₹13,679,693.06 (1.37 Cr)
Month 8: ₹13,197,367.91 (1.32 Cr)
Month 9: ₹12,969,030.14 (1.30 Cr)
Month 10: ₹13,274,847.93 (1.33 Cr)
Month 11: ₹13,281,696.61 (1.33 Cr)
Month 12: ₹13,386,132.52 (1.34 Cr)

In [66]:
comparison_export = pd.DataFrame({
    'year': df_model.iloc[-test_size:]['year'].values,
    'month': df_model.iloc[-test_size:]['month'].values,
    'actual_revenue': y_test.values,
    'predicted_revenue': lr_model.predict(X_test)
})

comparison_export.to_csv("actual_vs_predicted.csv", index=False)
print(comparison_export)

   year  month  actual_revenue  predicted_revenue
0  2025      7     12490297.99       1.240227e+07
1  2025      8     12102756.18       1.232699e+07
2  2025      9     10132338.42       9.687579e+06
3  2025     10     11242309.04       1.124428e+07
4  2025     11     12207746.02       1.265612e+07
5  2025     12     14154455.35       1.364855e+07

In [70]:
comparison_df.to_csv("model_comparison.csv")

In [69]:
comparison_df

                           MAPE (%)        RMSE
Linear Regression              2.37   344677.89
Ridge (Tuned)                  2.81   398593.65
Lasso (Tuned)                  4.11   546184.26
Random Forest (Tuned)          5.37   665990.96
Baseline (Naive Seasonal)     17.84  2748209.13
XGBoost (Tuned)               22.63  3003295.34
XGBoost (Simple)              23.60  3237992.12